spring:
  application:
    name: citronix
  datasource:
    url: jdbc:postgresql://localhost:5432/citronix
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
