name: Build & Deploy Citronix app

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-deploy:
    name: Build and Deploy Citronix app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile 
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/citronix:latest