name: Build & Deploy Citronix app

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-deploy:
    name: Build and Deploy Citronix app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: Run Tests
        run: |
          mvn test -Dtest=FermeServiceImplTest -X
        env:
          MAVEN_OPTS: "-Xmx1024m"

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: target/surefire-reports/