name: Build & Deploy Citronix app
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Run tests
        run: mvn clean test
      - name: Check test results
        if: failure()
        run: |
          echo "Tests failed! Workflow will stop."
          exit 1

  build:
    name: Build Application
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build with Maven
        run: mvn clean package -DskipTests
      - name: Verify build
        run: |
          if [ ! -f target/*.jar ]; then
            echo "Build failed - JAR file not found!"
            exit 1
          fi

  docker:
    name: Build and Push Docker
    needs: build
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build with Maven
        run: mvn clean package -DskipTests
      - name: Docker Login and Push
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/citronix:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/citronix:latest